version: '2'
services:
  start-mysql:
    image: mysql:8.0.16
    # volumes:
    #     - ~/volumes/jhipster/start/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=1371271347
      - MYSQL_DATABASE=start
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
